### ISSUE TITLE
Uncorrect spelling

### ISSUE THREAD

**Issue by lepon01** [JackSucksAtBot/bot#1]
![image](https://user-images.githubusercontent.com/13886925/46505179-292f1a80-c828-11e8-848e-66850776f889.png)
---
![image](https://user-images.githubusercontent.com/13886925/46505185-2b917480-c828-11e8-90e2-0b7a89a800b7.png)

**Comment by lepon01** [comment]
You can't have TOS which takes effect before it has been modified

![](https://cdn.bowser65.tk/s/ioHUZ7Dv.png)

**Comment by lepon01** [comment]
The search command doesn't actually search - It only provides link to search.

Therefore, `Searching..` is incorrect because it's not doing anything

![image](https://user-images.githubusercontent.com/13886925/46505366-c5f1b800-c828-11e8-9473-11a37aac137c.png)

**Comment by lepon01** [comment]
![image](https://user-images.githubusercontent.com/13886925/46505420-f2a5cf80-c828-11e8-9c77-10ff88641adf.png)

**Comment by Bowser65** [comment]
![lol](https://cdn.bowser65.tk/s/sspmL20t.png)

**Comment by Cairo2k18** [comment]
Fixed these, will be deployed in the update coming later.

**Comment by Cairo2k18** [comment]
> 
> 
> ![lol](https://camo.githubusercontent.com/02cefbf61b60a34c4447c7a34bf6fb355274dead/68747470733a2f2f63646e2e626f7773657236352e78797a2f732f7373706d4c3230742e706e67)

please note on the exact same version you're using I am able to use that command, so idk what happened there.

**Comment by Cairo2k18** [comment]
also just want to note modifying the discord client is against tos lmao

**Comment by lepon01** [comment]
**Certified Works On My Computer™**

**Comment by Cairo2k18** [comment]
> 
> 
> **Certified Works On My Computer™**

can you reproduce the jb!terms error or is it working fine?

**Comment by lepon01** [comment]
That was a weird unnecessary remark because it does not look like anyone has modified their client.

**Comment by Cairo2k18** [comment]
okay then

**Comment by lepon01** [comment]
I don't use the bot, so I don't know if the functionality works or not

I only posted an issue because I was reviewing your bot

**Comment by Cairo2k18** [comment]
ah, thanks anyway

**Comment by lepon01** [comment]
Unsubscribed
